[workspace]
resolver = "2"
members = [
    "thaw",
    "thaw_components",
    "thaw_macro",
    "thaw_utils",
    "demo",
    "demo_markdown",
]
exclude = ["examples"]

[workspace.package]
rust-version = "1.79"

[workspace.dependencies]
thaw = { version = "0.4.4", path = "./thaw" }
thaw_components = { version = "0.3.1", path = "./thaw_components" }
thaw_macro = { version = "0.1.0", path = "./thaw_macro" }
thaw_utils = { version = "0.1.1", path = "./thaw_utils" }

# leptos
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.8" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.8" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.8" }
reactive_stores = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.8" }

# web
wasm-bindgen = { version = "0.2.100" }